// Row-level mock datasets for the Dashboard Composer's "Ask Insights" mode —
// ask a real analytical question in plain English, get a chart that
// actually answers it (see insightsEngine.ts for the parsing/aggregation).
// Two domains ship on day one to prove the engine is domain-agnostic, not
// hand-tuned to one demo: a universal Regional Sales dataset (mirrors the
// classic BI-demo narrative) and a Procurement Ops dataset grounded in the
// real widget vocabulary already extracted from the user's own platform
// (see platformKnowledge.ts — "Top vendors", "Purchase by type and
// category", etc.). All values are generated by a fixed deterministic
// formula below, not Math.random(), so results are stable across renders
// and safe to record.

export interface InsightDimension { key: string; label: string; aliases: string[] }
export interface InsightMeasure { key: string; label: string; aliases: string[]; format: "currency" | "number" }
export interface InsightDomain {
  key: string;
  label: string;
  aliases: string[];
  rows: Record<string, string | number>[];
  dimensions: InsightDimension[];
  measures: InsightMeasure[];
  timeDimensionKey: string;
  timeOrder: string[];
  /** Key of a "Remarks"/"Reason"-style column, when the data carries one —
   *  powers root-cause and recommendation answers (see insightsEngine.ts). */
  reasonDimensionKey?: string;
}

// Trailing 6 months up to the app's "current" date (matches the Jul-2026
// dates already used elsewhere in this app's mock activity timestamps).
const MONTHS = ["Feb", "Mar", "Apr", "May", "Jun", "Jul"];
const MONTH_GROWTH = [0.82, 0.88, 0.94, 1.0, 1.08, 1.16]; // gentle upward trend, index-aligned with MONTHS

// --- Regional Sales -------------------------------------------------------
const REGIONS = ["North", "South", "East", "West"];
const REGION_STRENGTH: Record<string, number> = { North: 1.35, West: 1.15, East: 0.95, South: 0.75 };
const PRODUCTS = ["Laptops", "Monitors", "Accessories", "Networking Gear"];
const PRODUCT_STRENGTH: Record<string, number> = { Laptops: 1.4, "Networking Gear": 1.1, Monitors: 0.9, Accessories: 0.6 };
const UNIT_PRICE: Record<string, number> = { Laptops: 950, Monitors: 240, Accessories: 45, "Networking Gear": 310 };

function buildRegionalSalesRows(): Record<string, string | number>[] {
  const rows: Record<string, string | number>[] = [];
  for (let mi = 0; mi < MONTHS.length; mi++) {
    for (const region of REGIONS) {
      for (const product of PRODUCTS) {
        const seed = (region.length * 7 + product.length * 13 + mi * 31) % 17;
        const wobble = 0.9 + (seed / 17) * 0.3;
        const units = Math.round(40 * REGION_STRENGTH[region] * PRODUCT_STRENGTH[product] * MONTH_GROWTH[mi] * wobble);
        const revenue = Math.round(units * UNIT_PRICE[product]);
        rows.push({ region, product, month: MONTHS[mi], units, revenue });
      }
    }
  }
  return rows;
}

const REGIONAL_SALES: InsightDomain = {
  key: "regional-sales",
  label: "Regional Sales",
  aliases: ["sales", "selling", "sell", "revenue", "regional", "region"],
  rows: buildRegionalSalesRows(),
  dimensions: [
    { key: "region", label: "Region", aliases: ["region", "area", "zone", "territory"] },
    { key: "product", label: "Product", aliases: ["product", "module", "category", "item", "sku", "products"] },
  ],
  measures: [
    { key: "revenue", label: "Revenue", aliases: ["revenue", "sales", "money", "income"], format: "currency" },
    { key: "units", label: "Units", aliases: ["units", "unit", "volume", "quantity", "sold"], format: "number" },
  ],
  timeDimensionKey: "month",
  timeOrder: MONTHS,
};

// --- Procurement Ops -------------------------------------------------------
const VENDORS = ["Apex Supplies", "Meridian Traders", "Vantage Corp", "Silverline Logistics", "Crestpoint Materials"];
const VENDOR_STRENGTH: Record<string, number> = { "Apex Supplies": 1.3, "Vantage Corp": 1.15, "Meridian Traders": 1.0, "Crestpoint Materials": 0.85, "Silverline Logistics": 0.7 };
const CATEGORIES = ["Hardware", "Logistics", "Materials", "Services"];
const CATEGORY_STRENGTH: Record<string, number> = { Hardware: 1.25, Materials: 1.05, Logistics: 0.9, Services: 0.7 };
const AVG_PO_VALUE = 8200;

function buildProcurementRows(): Record<string, string | number>[] {
  const rows: Record<string, string | number>[] = [];
  for (let mi = 0; mi < MONTHS.length; mi++) {
    for (const vendor of VENDORS) {
      for (const category of CATEGORIES) {
        const seed = (vendor.length * 11 + category.length * 19 + mi * 23) % 19;
        const wobble = 0.85 + (seed / 19) * 0.35;
        const poCount = Math.max(1, Math.round(3 * VENDOR_STRENGTH[vendor] * CATEGORY_STRENGTH[category] * MONTH_GROWTH[mi] * wobble));
        const spend = Math.round(poCount * AVG_PO_VALUE * (0.9 + wobble * 0.1));
        rows.push({ vendor, category, month: MONTHS[mi], poCount, spend });
      }
    }
  }
  return rows;
}

const PROCUREMENT_OPS: InsightDomain = {
  key: "procurement-ops",
  label: "Procurement Ops",
  aliases: ["procurement", "purchase", "purchasing", "po", "vendor", "vendors", "spend"],
  rows: buildProcurementRows(),
  dimensions: [
    { key: "vendor", label: "Vendor", aliases: ["vendor", "supplier", "vendors", "suppliers"] },
    { key: "category", label: "Category", aliases: ["category", "categories", "type"] },
  ],
  measures: [
    { key: "spend", label: "Spend", aliases: ["spend", "spending", "cost", "amount"], format: "currency" },
    { key: "poCount", label: "PO count", aliases: ["po", "pos", "orders", "purchase orders", "count"], format: "number" },
  ],
  timeDimensionKey: "month",
  timeOrder: MONTHS,
};

export const INSIGHT_DOMAINS: InsightDomain[] = [REGIONAL_SALES, PROCUREMENT_OPS];
